version: 2

sources:
  - name: core
    database: stumpsndbails
    schema: Crictest
    tables:
      - name: ball_by_ball
      - name: match_info
      - name: player_info
models:
  - name: fact_balls
    description: "Fact table for ball by ball information of all cricket matches from the year 2002"
    columns:
      - name: match_id
        data_type: string
        description: "The id for the match. Currently this is the ID as used by ESPNCricinfo."

      - name: striker
        data_type: string
        description: "The name of the batter who faced the delivery"
        tests:
          - not_null
              

      - name: non_striker
        data_type: string
        description: "The name of the non-striker during the delivery."
        tests:
          - not_null

      - name: bowler
        data_type: string
        description: "The name of the bowler during the delivery."
        tests:
          - not_null

      - name: innings
        data_type: int64
        description: "The number of the innings in which the delivery took place."
        tests:
          - not_null

      - name: overs
        data_type: int64
        description: "An identifier for the delivery (such as 23.5) specifies the particular ball (in that case 24th over)"
        

      - name: ball
        data_type: int64
        description: "An identifier for the delivery (such as 23.5) specifies the particular ball (in that case the 5th ball)"

      - name: runs_off_bat
        data_type: int64
        description: "The total number of runs scored by the batter off the ball. If the batter failed to score this will show 0"

      - name: extras
        data_type: int64
        description: ""

      - name: extras_type
        data_type: string
        description: "The total number of runs conceded via extras off the ball. If no extras were conceded this will show 0."

      - name: wicket_flg
        data_type: string
        description: ""

      - name: wicket_type
        data_type: string
        description: "If a wicket fell on this delivery then this will be the kind of dismissal that took place. This will be one of bowled, caught, caught and bowled, lbw, stumped, run out, retired hurt, hit wicket, obstructing the field, hit the ball twice, handled the ball, or timed out. If no dismissals took place this will be an empty string."

  - name: dim_players
    description: ""
    columns:
      - name: player_id
        data_type: string
        description: ""

      - name: player_name
        data_type: string
        description: ""

      - name: team
        data_type: string
        description: ""

      - name: match_id
        data_type: int64
        description: ""

  - name: dim_matches
    description: ""
    columns:
      - name: match_id
        data_type: int64
        description: ""

      - name: team
        data_type: string
        description: ""

      - name: dates_played
        data_type: date
        description: ""

      - name: event
        data_type: string
        description: ""

      - name: venue
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: gender
        data_type: string
        description: ""

      - name: winner
        data_type: string
        description: ""

      - name: method
        data_type: string
        description: ""

      - name: player_of_match
        data_type: string
        description: ""

      - name: other_result
        data_type: string
        description: ""

      - name: umpire
        data_type: string
        description: ""

  - name: dim_date
    description: ""
    columns:
      - name: cal_date
        data_type: date
        description: ""

      - name: cal_year
        data_type: int64
        description: ""

      - name: cal_year_day
        data_type: int64
        description: ""

      - name: cal_quarter
        data_type: int64
        description: ""

      - name: cal_month
        data_type: int64
        description: ""

      - name: cal_month_name
        data_type: string
        description: ""

      - name: cal_month_day
        data_type: int64
        description: ""

      - name: cal_week
        data_type: int64
        description: ""

      - name: cal_week_day
        data_type: int64
        description: ""

      - name: cal_day_name
        data_type: string
        description: ""

      - name: id
        data_type: int64
        description: ""

  - name: fact_batsman_info
    description: ""
    columns:
      - name: match_id
        data_type: int64
        description: ""

      - name: match_year
        data_type: int64
        description: ""

      - name: event
        data_type: string
        description: ""

      - name: team_for
        data_type: string
        description: ""

      - name: team_against
        data_type: string
        description: ""

      - name: batsman
        data_type: string
        description: ""

      - name: innings
        data_type: int64
        description: ""

      - name: runs
        data_type: int64
        description: ""

      - name: balls_faced
        data_type: int64
        description: ""

      - name: 0s
        data_type: int64
        description: ""

      - name: 4s
        data_type: int64
        description: ""

      - name: 6s
        data_type: int64
        description: ""

      - name: strikerate
        data_type: float64
        description: ""
