version: '3'
services:
  mageorchestrator:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: DockerFile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - /home/stumpsndbails/stumpsNDbails/mage/:/home/src/
      - /home/stumpsndbails/stumpsNDbails/mage/secrets/:/home/src/secrets
      - /home/stumpsndbails/stumpsNDbails/secrets/stumpsndbails-b4fe9300c0a1.json:/home/src/secrets/service-account.json
    restart: on-failure:5