triggers:
- envs: []
  last_enabled_at: 2024-02-27 04:49:33.646512
  name: Every day load
  pipeline_uuid: rawdataingesterandcleaner
  schedule_interval: 0 6 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-27 04:48:00
  status: active
  variables: {}
- envs: []
  last_enabled_at: 2024-02-27 19:21:05.881878
  name: chromatic snowflake
  pipeline_uuid: rawdataingesterandcleaner
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-26 19:20:00
  status: active
  variables: {}
